---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nifi
  labels:
    name: nifi
    app: nifi
  annotations:
    app.kubernetes.io/name: nifi
    app.kubernetes.io/part-of: nifi
spec:
  selector:
    matchLabels:
      app: nifi
  template:
    metadata:
      labels:
        app: nifi
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
        kubernetes.io/arch: amd64
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - nifi
      restartPolicy: Always
      containers:
      - name: nifi
        image: docker.io/apache/nifi:1.13.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: nifi
        - containerPort: 8082
          name: cluster
        env:
          - name: NIFI_WEB_HTTP_HOST
            value: "0.0.0.0"
          - name: NIFI_WEB_HTTP_PORT
            value: "8080"
          - name: NIFI_CLUSTER_IS_NODE
            value: "true"
          - name: NIFI_CLUSTER_NODE_PROTOCOL_PORT
            value: "8082"
          - name: NIFI_CLUSTER_NODE_PROTOCOL_MAX_THREADS
            value: "20"
          - name: NIFI_CLUSTER_NODE_ADDRESS
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: NIFI_ZK_CONNECT_STRING
            value: "zookeeper:2181"
          - name: NIFI_ZK_ROOT_NODE
            value: "/nifi"
          - name: NIFI_ELECTION_MAX_WAIT
            value: "10 sec"
          - name: NIFI_JVM_HEAP_INIT
            value: "3g"
          - name: NIFI_JVM_HEAP_MAX
            value: "4g"
        volumeMounts:
          - name: flow-xml
            mountPath: /opt/nifi/nifi-current/conf
            subPath: conf
        livenessProbe:
          exec:
            command:
              - pgrep
              - java
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          tcpSocket:
              port: 8080
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        resources:
          requests:
            cpu: 300m
            memory: 3Gi
          limits:
            cpu: 400m
            memory: 4Gi
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          runAsGroup: 1000
          runAsUser: 1000
          capabilities:
            drop:
              - ALL
            add:
              - NET_BIND_SERVICE
              - SYS_TIME
      volumes:
        - name: flow-xml
          emptyDir: {}
