---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nifi

resources:
- namespace.yml
- statefulset.yml
- secret.yml
- service.yml
# Set $(HOST) to a valid hostname before enabling ingress
# - ingress.yml
