---
name: CI
on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/docker.yml"
      - "deployment/"
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/docker.yml"
      - "deployment/"

jobs:
  k8s-test:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ ! contains(github.ref, 'master') }}
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run K8s test
        run: |
          kubectl cluster-info
          export NS=`cat deployment/kustomization.yml  | grep namespace | awk '{ print $2 }'`
          if [ -z "$NS" ]; then
            export NS='data'
          fi
          kubectl create namespace $NS
          kubectl apply -n $NS -k deployment/
          kubectl get all -n $NS

  auto-approve:
    runs-on: ubuntu-latest
    needs: [k8s-test]
    if: ${{ github.event_name == 'pull_request' }}
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - uses: hmarr/auto-approve-action@v2
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"